version: '3'

services:

  jenkins:
    build:
      context: .
      dockerfile: "jenkins.Dockerfile"
    container_name: "${project}"
    env_file: .env
    image: "${image}"
    networks: 
      - net
    ports:
      - "${http_port}:8080/tcp"
      - "${agent_port}:50000/tcp"
    privileged: true
    restart: on-failure
    user: root
    volumes:
      - certs:${JENKINS_HOME}/certs/client:ro
      - data:${JENKINS_HOME}
    working_dir: "${JENKINS_HOME}"

  alpine:
    build:
      args:
        - key=${ssh_key}
        - username=${username}
        - port=${ssh_port}
      context: .
      dockerfile: "alpine.Dockerfile"
    container_name: "${project}-alpine-controller"
    image: "alpine/jenkins:3.17"
    networks: 
      - net
    volumes:
      - data:${JENKINS_HOME}
    restart: on-failure
  centos:
    build:
      args:
        - key=${ssh_key}
        - username=${username}
        - port=${ssh_port}
      context: .
      dockerfile: "centos.Dockerfile"
    container_name: "${project}-centos-agent"
    image: "centos/jenkins:7"
    networks: 
      - net
    restart: on-failure
    volumes:
      - data:${JENKINS_HOME}
  debian:
    build:
      args:
        - key=${ssh_key}
        - username=${username}
        - port=${ssh_port}
      context: .
      dockerfile: "debian.Dockerfile"
    container_name: "${project}-debian-agent"
    image: "debian/jenkins:11"
    networks: 
      - net
    restart: on-failure
    volumes:
      - data:${JENKINS_HOME}
  ubuntu:
    build:
      args:
        - key=${ssh_key}
        - username=${username}
        - port=${ssh_port}
      context: .
      dockerfile: "ubuntu.Dockerfile"
    container_name: "${project}-ubuntu-agent"
    image: "ubuntu/jenkins:22.04"
    networks: 
      - net
    restart: on-failure
    volumes:
      - data:${JENKINS_HOME}

networks: 
    net:
      driver: bridge

volumes:
  certs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${certs_dir}"
    name: ${volume_certs}

  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${data_dir}"
    name: ${volume_data}

